/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.java.seven.days.of.code.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
